#	video
#1080p = 699
#360p = 696
#
#	audio
#WebM(Opus) 160Kbps = 251

[servers]
piped=[]
invidious=[]

#these channels have been choosen randomly

[[channels]]
#BeerBiceps
channelid='UCPxMZIFE856tbTfdkdjzTSQ'
format=251

[[channels]]
#Vsauce
channelid='UC6nSFpj9HTCZ5t-N3Rm3-HA'
format=696
